:libVersion: 0.1.7

# ADAL

image:https://api.bintray.com/packages/jmspt/maven/adal/images/download.svg[Build Status,link=https://bintray.com/jmspt/maven/adal/_latestVersion]

Android Development Accelaration Library

Add the dependency in the form:
[source, groovy, subs='attributes']
dependencies {
  /* Include all modules */
  compile 'com.massivedisaster.adal:adal:{libVersion}'
  /* Specific modules*/
  compile 'com.massivedisaster.adal:adal-accounts:{libVersion}'
  compile 'com.massivedisaster.adal:adal-adapters:{libVersion}'
  compile 'com.massivedisaster.adal:adal-analytics:{libVersion}'
  compile 'com.massivedisaster.adal:adal-bus:{libVersion}'
  compile 'com.massivedisaster.adal:adal-fragments:{libVersion}'
  compile 'com.massivedisaster.adal:adal-managers:{libVersion}'
  compile 'com.massivedisaster.adal:adal-network:{libVersion}'
  compile 'com.massivedisaster.adal:adal-utils:{libVersion}'
  compile 'com.massivedisaster.adal:adal-location:{libVersion}'
}

### License
link:LICENSE.md[GNU LESSER GENERAL PUBLIC LICENSE]
